/* Generated by Yosys 0.57 (git sha1 3aca86049, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* src = "../rtl/rs232/u_rec.v:4.1-178.10" *)
module u_rec(sys_rst_l, sys_clk, uart_dataH, rec_dataH, rec_readyH);
  (* src = "../rtl/rs232/u_rec.v:20.9-20.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "../rtl/rs232/u_rec.v:21.9-21.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "../rtl/rs232/u_rec.v:23.9-23.19" *)
  input uart_dataH;
  wire uart_dataH;
  (* src = "../rtl/rs232/u_rec.v:25.14-25.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "../rtl/rs232/u_rec.v:26.10-26.20" *)
  output rec_readyH;
  wire rec_readyH;
  (* src = "../rtl/rs232/u_rec.v:71.1-74.43" *)
  wire [3:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/rs232/u_rec.v:147.5-147.5|../rtl/rs232/u_rec.v:108.3-165.10|/usr/local/bin/../share/yosys/techmap.v:572.28-572.29" *)
  (* unused_bits = "6 7 8 9 10" *)
  wire [14:0] _073_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/rs232/u_rec.v:74.25-74.42|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _074_;
  (* force_downto = 32'd1 *)
  (* src = "../rtl/rs232/u_rec.v:87.37-87.54|../rtl/rs232/u_rec.v:74.25-74.42|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _075_;
  (* src = "../rtl/rs232/u_rec.v:32.12-32.25" *)
  wire [3:0] bitCell_cntrH;
  (* src = "../rtl/rs232/u_rec.v:47.9-47.12" *)
  wire ena;
  (* src = "../rtl/rs232/u_rec.v:30.12-30.22" *)
  wire [2:0] next_state;
  (* src = "../rtl/rs232/u_rec.v:34.12-34.21" *)
  wire [7:0] par_dataH;
  (* src = "../rtl/rs232/u_rec.v:31.8-31.16" *)
  wire rec_datH;
  (* src = "../rtl/rs232/u_rec.v:31.18-31.30" *)
  wire rec_datSyncH;
  (* src = "../rtl/rs232/u_rec.v:39.8-39.23" *)
  wire rec_readyH_temp;
  (* src = "../rtl/rs232/u_rec.v:40.8-40.20" *)
  wire rec_readyInH;
  (* src = "../rtl/rs232/u_rec.v:36.12-36.25" *)
  wire [3:0] recd_bitCntrH;
  (* src = "../rtl/rs232/u_rec.v:30.24-30.29" *)
  wire [2:0] state;
  INV_X1 _076_ (
    .A(recd_bitCntrH[3]),
    .ZN(_039_)
  );
  INV_X1 _077_ (
    .A(_073_[13]),
    .ZN(_040_)
  );
  INV_X1 _078_ (
    .A(ena),
    .ZN(_041_)
  );
  NOR3_X1 _079_ (
    .A1(state[2]),
    .A2(state[1]),
    .A3(_004_),
    .ZN(_042_)
  );
  AND2_X1 _080_ (
    .A1(rec_datH),
    .A2(_042_),
    .ZN(_043_)
  );
  NAND2_X1 _081_ (
    .A1(rec_datH),
    .A2(_042_),
    .ZN(_044_)
  );
  NOR3_X1 _082_ (
    .A1(state[0]),
    .A2(state[1]),
    .A3(_001_),
    .ZN(_045_)
  );
  AOI21_X1 _083_ (
    .A(_045_),
    .B1(_042_),
    .B2(rec_datH),
    .ZN(_046_)
  );
  AOI22_X1 _084_ (
    .A1(_075_[0]),
    .A2(_045_),
    .B1(_046_),
    .B2(recd_bitCntrH[0]),
    .ZN(_047_)
  );
  INV_X1 _085_ (
    .A(_047_),
    .ZN(_009_)
  );
  NAND2_X1 _086_ (
    .A1(recd_bitCntrH[1]),
    .A2(_046_),
    .ZN(_048_)
  );
  AND2_X1 _087_ (
    .A1(recd_bitCntrH[0]),
    .A2(recd_bitCntrH[1]),
    .ZN(_049_)
  );
  OAI21_X1 _088_ (
    .A(_045_),
    .B1(recd_bitCntrH[1]),
    .B2(recd_bitCntrH[0]),
    .ZN(_050_)
  );
  OAI21_X1 _089_ (
    .A(_048_),
    .B1(_049_),
    .B2(_050_),
    .ZN(_010_)
  );
  AOI21_X1 _090_ (
    .A(recd_bitCntrH[2]),
    .B1(_045_),
    .B2(_049_),
    .ZN(_051_)
  );
  NAND3_X1 _091_ (
    .A1(recd_bitCntrH[2]),
    .A2(_045_),
    .A3(_049_),
    .ZN(_052_)
  );
  OAI21_X1 _092_ (
    .A(_052_),
    .B1(_045_),
    .B2(_044_),
    .ZN(_053_)
  );
  NOR2_X1 _093_ (
    .A1(_051_),
    .A2(_053_),
    .ZN(_011_)
  );
  AND2_X1 _094_ (
    .A1(_039_),
    .A2(_052_),
    .ZN(_054_)
  );
  AOI21_X1 _095_ (
    .A(_054_),
    .B1(_053_),
    .B2(recd_bitCntrH[3]),
    .ZN(_012_)
  );
  MUX2_X1 _096_ (
    .A(par_dataH[7]),
    .B(rec_datH),
    .S(_045_),
    .Z(_013_)
  );
  MUX2_X1 _097_ (
    .A(par_dataH[0]),
    .B(par_dataH[1]),
    .S(_045_),
    .Z(_014_)
  );
  MUX2_X1 _098_ (
    .A(par_dataH[1]),
    .B(par_dataH[2]),
    .S(_045_),
    .Z(_015_)
  );
  MUX2_X1 _099_ (
    .A(par_dataH[2]),
    .B(par_dataH[3]),
    .S(_045_),
    .Z(_016_)
  );
  MUX2_X1 _100_ (
    .A(par_dataH[3]),
    .B(par_dataH[4]),
    .S(_045_),
    .Z(_017_)
  );
  MUX2_X1 _101_ (
    .A(par_dataH[4]),
    .B(par_dataH[5]),
    .S(_045_),
    .Z(_018_)
  );
  MUX2_X1 _102_ (
    .A(par_dataH[5]),
    .B(par_dataH[6]),
    .S(_045_),
    .Z(_019_)
  );
  MUX2_X1 _103_ (
    .A(par_dataH[6]),
    .B(par_dataH[7]),
    .S(_045_),
    .Z(_020_)
  );
  NOR3_X1 _104_ (
    .A1(state[1]),
    .A2(_004_),
    .A3(_001_),
    .ZN(_055_)
  );
  NOR2_X1 _105_ (
    .A1(_045_),
    .A2(_055_),
    .ZN(_056_)
  );
  NOR3_X1 _106_ (
    .A1(state[2]),
    .A2(_004_),
    .A3(_005_),
    .ZN(_057_)
  );
  NOR4_X1 _107_ (
    .A1(bitCell_cntrH[0]),
    .A2(_007_),
    .A3(_006_),
    .A4(_008_),
    .ZN(_058_)
  );
  AND2_X1 _108_ (
    .A1(_057_),
    .A2(_058_),
    .ZN(next_state[2])
  );
  NOR3_X1 _109_ (
    .A1(state[0]),
    .A2(state[2]),
    .A3(_005_),
    .ZN(_059_)
  );
  NOR4_X1 _110_ (
    .A1(bitCell_cntrH[1]),
    .A2(bitCell_cntrH[3]),
    .A3(bitCell_cntrH[0]),
    .A4(_007_),
    .ZN(_060_)
  );
  NAND2_X1 _111_ (
    .A1(_059_),
    .A2(_060_),
    .ZN(_061_)
  );
  AOI221_X1 _112_ (
    .A(_042_),
    .B1(_057_),
    .B2(_058_),
    .C1(_059_),
    .C2(_060_),
    .ZN(_021_)
  );
  NAND2_X1 _113_ (
    .A1(_056_),
    .A2(_021_),
    .ZN(_022_)
  );
  AND3_X1 _114_ (
    .A1(_074_[0]),
    .A2(_056_),
    .A3(_021_),
    .ZN(_000_[0])
  );
  NAND2_X1 _115_ (
    .A1(bitCell_cntrH[1]),
    .A2(bitCell_cntrH[0]),
    .ZN(_023_)
  );
  XNOR2_X1 _116_ (
    .A(bitCell_cntrH[1]),
    .B(bitCell_cntrH[0]),
    .ZN(_024_)
  );
  NOR2_X1 _117_ (
    .A1(_022_),
    .A2(_024_),
    .ZN(_000_[1])
  );
  NAND3_X1 _118_ (
    .A1(bitCell_cntrH[1]),
    .A2(bitCell_cntrH[2]),
    .A3(bitCell_cntrH[0]),
    .ZN(_025_)
  );
  XOR2_X1 _119_ (
    .A(bitCell_cntrH[2]),
    .B(_023_),
    .Z(_026_)
  );
  NOR2_X1 _120_ (
    .A1(_022_),
    .A2(_026_),
    .ZN(_000_[2])
  );
  XOR2_X1 _121_ (
    .A(bitCell_cntrH[3]),
    .B(_025_),
    .Z(_027_)
  );
  NOR2_X1 _122_ (
    .A1(_022_),
    .A2(_027_),
    .ZN(_000_[3])
  );
  OR2_X1 _123_ (
    .A1(_043_),
    .A2(_055_),
    .ZN(rec_readyInH)
  );
  NOR4_X1 _124_ (
    .A1(recd_bitCntrH[0]),
    .A2(recd_bitCntrH[1]),
    .A3(recd_bitCntrH[2]),
    .A4(_003_),
    .ZN(_028_)
  );
  NOR4_X1 _125_ (
    .A1(state[2]),
    .A2(_004_),
    .A3(_005_),
    .A4(_058_),
    .ZN(_029_)
  );
  AOI21_X1 _126_ (
    .A(_029_),
    .B1(_028_),
    .B2(_057_),
    .ZN(_030_)
  );
  NAND4_X1 _127_ (
    .A1(_044_),
    .A2(_056_),
    .A3(_061_),
    .A4(_030_),
    .ZN(next_state[0])
  );
  NAND2_X1 _128_ (
    .A1(_040_),
    .A2(_060_),
    .ZN(_031_)
  );
  AOI21_X1 _129_ (
    .A(_029_),
    .B1(_042_),
    .B2(_073_[13]),
    .ZN(_032_)
  );
  AOI21_X1 _130_ (
    .A(_045_),
    .B1(_059_),
    .B2(_031_),
    .ZN(_033_)
  );
  NAND2_X1 _131_ (
    .A1(_032_),
    .A2(_033_),
    .ZN(next_state[1])
  );
  AND4_X1 _132_ (
    .A1(par_dataH[7]),
    .A2(par_dataH[0]),
    .A3(par_dataH[1]),
    .A4(par_dataH[2]),
    .ZN(_034_)
  );
  AND2_X1 _133_ (
    .A1(par_dataH[4]),
    .A2(_041_),
    .ZN(rec_dataH[4])
  );
  NAND4_X1 _134_ (
    .A1(_001_),
    .A2(_003_),
    .A3(_074_[0]),
    .A4(_002_),
    .ZN(_035_)
  );
  NAND4_X1 _135_ (
    .A1(state[1]),
    .A2(bitCell_cntrH[1]),
    .A3(bitCell_cntrH[2]),
    .A4(bitCell_cntrH[3]),
    .ZN(_036_)
  );
  NAND4_X1 _136_ (
    .A1(par_dataH[3]),
    .A2(par_dataH[5]),
    .A3(par_dataH[6]),
    .A4(state[0]),
    .ZN(_037_)
  );
  NOR3_X1 _137_ (
    .A1(_035_),
    .A2(_036_),
    .A3(_037_),
    .ZN(_038_)
  );
  AND4_X1 _138_ (
    .A1(_049_),
    .A2(_034_),
    .A3(rec_dataH[4]),
    .A4(_038_),
    .ZN(ena)
  );
  AND2_X1 _139_ (
    .A1(par_dataH[0]),
    .A2(_041_),
    .ZN(rec_dataH[0])
  );
  AND2_X1 _140_ (
    .A1(par_dataH[1]),
    .A2(_041_),
    .ZN(rec_dataH[1])
  );
  AND2_X1 _141_ (
    .A1(par_dataH[2]),
    .A2(_041_),
    .ZN(rec_dataH[2])
  );
  AND2_X1 _142_ (
    .A1(par_dataH[3]),
    .A2(_041_),
    .ZN(rec_dataH[3])
  );
  AND2_X1 _143_ (
    .A1(par_dataH[5]),
    .A2(_041_),
    .ZN(rec_dataH[5])
  );
  AND2_X1 _144_ (
    .A1(par_dataH[6]),
    .A2(_041_),
    .ZN(rec_dataH[6])
  );
  AND2_X1 _145_ (
    .A1(par_dataH[7]),
    .A2(_041_),
    .ZN(rec_dataH[7])
  );
  AND2_X1 _146_ (
    .A1(rec_readyH_temp),
    .A2(_041_),
    .ZN(rec_readyH)
  );
  (* src = "../rtl/rs232/u_rec.v:85.1-88.42" *)
  DFFR_X1 _147_ (
    .CK(sys_clk),
    .D(_009_),
    .Q(recd_bitCntrH[0]),
    .QN(_075_[0]),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:85.1-88.42" *)
  DFFR_X1 _148_ (
    .CK(sys_clk),
    .D(_010_),
    .Q(recd_bitCntrH[1]),
    .QN(_070_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:85.1-88.42" *)
  DFFR_X1 _149_ (
    .CK(sys_clk),
    .D(_011_),
    .Q(recd_bitCntrH[2]),
    .QN(_002_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:85.1-88.42" *)
  DFFR_X1 _150_ (
    .CK(sys_clk),
    .D(_012_),
    .Q(recd_bitCntrH[3]),
    .QN(_003_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:171.1-173.40" *)
  DFFR_X1 _151_ (
    .CK(sys_clk),
    .D(rec_readyInH),
    .Q(rec_readyH_temp),
    .QN(_071_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:93.1-95.28" *)
  DFFS_X1 _152_ (
    .CK(sys_clk),
    .D(next_state[0]),
    .Q(state[0]),
    .QN(_004_),
    .SN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:93.1-95.28" *)
  DFFR_X1 _153_ (
    .CK(sys_clk),
    .D(next_state[1]),
    .Q(state[1]),
    .QN(_005_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:93.1-95.28" *)
  DFFR_X1 _154_ (
    .CK(sys_clk),
    .D(next_state[2]),
    .Q(state[2]),
    .QN(_001_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _155_ (
    .CK(sys_clk),
    .D(_013_),
    .Q(par_dataH[7]),
    .QN(_072_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:71.1-74.43" *)
  DFFR_X1 _156_ (
    .CK(sys_clk),
    .D(_000_[0]),
    .Q(bitCell_cntrH[0]),
    .QN(_074_[0]),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:71.1-74.43" *)
  DFFR_X1 _157_ (
    .CK(sys_clk),
    .D(_000_[1]),
    .Q(bitCell_cntrH[1]),
    .QN(_006_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:71.1-74.43" *)
  DFFR_X1 _158_ (
    .CK(sys_clk),
    .D(_000_[2]),
    .Q(bitCell_cntrH[2]),
    .QN(_007_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:71.1-74.43" *)
  DFFR_X1 _159_ (
    .CK(sys_clk),
    .D(_000_[3]),
    .Q(bitCell_cntrH[3]),
    .QN(_008_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:61.1-68.6" *)
  DFFS_X1 _160_ (
    .CK(sys_clk),
    .D(rec_datSyncH),
    .Q(rec_datH),
    .QN(_073_[13]),
    .SN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:61.1-68.6" *)
  DFFS_X1 _161_ (
    .CK(sys_clk),
    .D(uart_dataH),
    .Q(rec_datSyncH),
    .QN(_069_),
    .SN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _162_ (
    .CK(sys_clk),
    .D(_014_),
    .Q(par_dataH[0]),
    .QN(_068_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _163_ (
    .CK(sys_clk),
    .D(_015_),
    .Q(par_dataH[1]),
    .QN(_067_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _164_ (
    .CK(sys_clk),
    .D(_016_),
    .Q(par_dataH[2]),
    .QN(_066_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _165_ (
    .CK(sys_clk),
    .D(_017_),
    .Q(par_dataH[3]),
    .QN(_065_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _166_ (
    .CK(sys_clk),
    .D(_018_),
    .Q(par_dataH[4]),
    .QN(_064_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _167_ (
    .CK(sys_clk),
    .D(_019_),
    .Q(par_dataH[5]),
    .QN(_063_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_rec.v:77.1-82.6" *)
  DFFR_X1 _168_ (
    .CK(sys_clk),
    .D(_020_),
    .Q(par_dataH[6]),
    .QN(_062_),
    .RN(sys_rst_l)
  );
  assign { _073_[14], _073_[12:11], _073_[5:0] } = { 1'h0, rec_datH, 7'h19 };
  assign _074_[31:1] = { 28'h0000000, bitCell_cntrH[3:1] };
  assign _075_[31:1] = { 28'h0000000, recd_bitCntrH[3:1] };
endmodule

(* src = "../rtl/rs232/u_xmit.v:4.1-178.10" *)
module u_xmit(sys_clk, sys_rst_l, uart_xmitH, xmitH, xmit_dataH, xmit_doneH);
  (* src = "../rtl/rs232/u_xmit.v:15.9-15.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "../rtl/rs232/u_xmit.v:16.9-16.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "../rtl/rs232/u_xmit.v:17.10-17.20" *)
  output uart_xmitH;
  wire uart_xmitH;
  (* src = "../rtl/rs232/u_xmit.v:18.9-18.14" *)
  input xmitH;
  wire xmitH;
  (* src = "../rtl/rs232/u_xmit.v:19.13-19.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "../rtl/rs232/u_xmit.v:20.10-20.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "../rtl/rs232/u_xmit.v:24.12-24.22" *)
  wire [2:0] next_state;
  (* src = "../rtl/rs232/u_xmit.v:24.24-24.29" *)
  wire [2:0] state;
  (* src = "../rtl/rs232/u_xmit.v:35.8-35.20" *)
  wire xmit_doneInH;
  INV_X1 _12_ (
    .A(state[1]),
    .ZN(_03_)
  );
  INV_X1 _13_ (
    .A(_02_),
    .ZN(_04_)
  );
  NOR3_X1 _14_ (
    .A1(state[1]),
    .A2(_01_),
    .A3(_00_),
    .ZN(next_state[2])
  );
  OAI33_X1 _15_ (
    .A1(state[1]),
    .A2(state[0]),
    .A3(_00_),
    .B1(_02_),
    .B2(state[2]),
    .B3(_01_),
    .ZN(_05_)
  );
  INV_X1 _16_ (
    .A(_05_),
    .ZN(_06_)
  );
  OR2_X1 _17_ (
    .A1(next_state[2]),
    .A2(_05_),
    .ZN(next_state[0])
  );
  OR2_X1 _18_ (
    .A1(state[0]),
    .A2(state[2]),
    .ZN(_07_)
  );
  AOI21_X1 _19_ (
    .A(_04_),
    .B1(xmitH),
    .B2(_03_),
    .ZN(_08_)
  );
  OAI21_X1 _20_ (
    .A(_06_),
    .B1(_07_),
    .B2(_08_),
    .ZN(next_state[1])
  );
  NOR3_X1 _21_ (
    .A1(state[1]),
    .A2(state[0]),
    .A3(state[2]),
    .ZN(_09_)
  );
  NOR2_X1 _22_ (
    .A1(next_state[2]),
    .A2(_09_),
    .ZN(_10_)
  );
  NOR2_X1 _23_ (
    .A1(_05_),
    .A2(_10_),
    .ZN(uart_xmitH)
  );
  NOR3_X1 _24_ (
    .A1(state[1]),
    .A2(xmitH),
    .A3(_07_),
    .ZN(xmit_doneInH)
  );
  (* src = "../rtl/rs232/u_xmit.v:173.1-175.35" *)
  DFFR_X1 _25_ (
    .CK(sys_clk),
    .D(xmit_doneInH),
    .Q(xmit_doneH),
    .QN(_11_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_xmit.v:73.1-75.28" *)
  DFFR_X1 _26_ (
    .CK(sys_clk),
    .D(next_state[0]),
    .Q(state[0]),
    .QN(_01_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_xmit.v:73.1-75.28" *)
  DFFR_X1 _27_ (
    .CK(sys_clk),
    .D(next_state[1]),
    .Q(state[1]),
    .QN(_02_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/u_xmit.v:73.1-75.28" *)
  DFFR_X1 _28_ (
    .CK(sys_clk),
    .D(next_state[2]),
    .Q(state[2]),
    .QN(_00_),
    .RN(sys_rst_l)
  );
endmodule

(* top =  1  *)
(* src = "../rtl/rs232/uart.v:3.1-78.10" *)
module uart(sys_clk, sys_rst_l, uart_XMIT_dataH, xmitH, xmit_dataH, xmit_doneH, uart_REC_dataH, rec_dataH, rec_readyH);
  (* src = "../rtl/rs232/uart.v:17.9-17.16" *)
  input sys_clk;
  wire sys_clk;
  (* src = "../rtl/rs232/uart.v:18.9-18.18" *)
  input sys_rst_l;
  wire sys_rst_l;
  (* src = "../rtl/rs232/uart.v:19.10-19.25" *)
  output uart_XMIT_dataH;
  wire uart_XMIT_dataH;
  (* src = "../rtl/rs232/uart.v:20.9-20.14" *)
  input xmitH;
  wire xmitH;
  (* src = "../rtl/rs232/uart.v:21.13-21.23" *)
  input [7:0] xmit_dataH;
  wire [7:0] xmit_dataH;
  (* src = "../rtl/rs232/uart.v:22.10-22.20" *)
  output xmit_doneH;
  wire xmit_doneH;
  (* src = "../rtl/rs232/uart.v:24.9-24.23" *)
  input uart_REC_dataH;
  wire uart_REC_dataH;
  (* src = "../rtl/rs232/uart.v:25.14-25.23" *)
  output [7:0] rec_dataH;
  wire [7:0] rec_dataH;
  (* src = "../rtl/rs232/uart.v:26.10-26.20" *)
  output rec_readyH;
  wire rec_readyH;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "../rtl/rs232/uart.v:30.17-30.30" *)
  wire [7:0] rec_dataH_rec;
  (* src = "../rtl/rs232/uart.v:29.17-29.31" *)
  wire [7:0] rec_dataH_temp;
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _16_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[0]),
    .Q(rec_dataH_temp[0]),
    .QN(_01_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _17_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[1]),
    .Q(rec_dataH_temp[1]),
    .QN(_02_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _18_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[2]),
    .Q(rec_dataH_temp[2]),
    .QN(_03_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _19_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[3]),
    .Q(rec_dataH_temp[3]),
    .QN(_04_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _20_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[4]),
    .Q(rec_dataH_temp[4]),
    .QN(_05_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _21_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[5]),
    .Q(rec_dataH_temp[5]),
    .QN(_06_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _22_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[6]),
    .Q(rec_dataH_temp[6]),
    .QN(_07_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:69.1-76.6" *)
  DFFR_X1 _23_ (
    .CK(rec_readyH),
    .D(rec_dataH_rec[7]),
    .Q(rec_dataH_temp[7]),
    .QN(_08_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _24_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[0]),
    .Q(rec_dataH[0]),
    .QN(_09_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _25_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[1]),
    .Q(rec_dataH[1]),
    .QN(_10_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _26_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[2]),
    .Q(rec_dataH[2]),
    .QN(_11_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _27_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[3]),
    .Q(rec_dataH[3]),
    .QN(_12_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _28_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[4]),
    .Q(rec_dataH[4]),
    .QN(_13_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _29_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[5]),
    .Q(rec_dataH[5]),
    .QN(_14_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _30_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[6]),
    .Q(rec_dataH[6]),
    .QN(_15_),
    .RN(sys_rst_l)
  );
  (* src = "../rtl/rs232/uart.v:59.1-66.6" *)
  DFFR_X1 _31_ (
    .CK(sys_clk),
    .D(rec_dataH_temp[7]),
    .Q(rec_dataH[7]),
    .QN(_00_),
    .RN(sys_rst_l)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/rs232/uart.v:47.7-57.6" *)
  u_rec iRECEIVER (
    .rec_dataH(rec_dataH_rec),
    .rec_readyH(rec_readyH),
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_dataH(uart_REC_dataH)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/rs232/uart.v:35.9-42.5" *)
  u_xmit iXMIT (
    .sys_clk(sys_clk),
    .sys_rst_l(sys_rst_l),
    .uart_xmitH(uart_XMIT_dataH),
    .xmitH(xmitH),
    .xmit_dataH(xmit_dataH),
    .xmit_doneH(xmit_doneH)
  );
endmodule
